USE BDGIS;

-- TABELA: dbo.GIS_T1126A_FUNCIONARIO

-- Eliminação da tabela, se existir.


IF EXISTS 
(
	SELECT *
	FROM sys.check_constraints 
	WHERE object_id = OBJECT_ID(N'dbo.CK_GIS_T1126A_FUNCIONARIO')
		AND parent_object_id = OBJECT_ID(N'dbo.GIS_T1126A_FUNCIONARIO')
) 
	ALTER TABLE dbo.GIS_T1126A_FUNCIONARIO
	DROP CONSTRAINT CK_GIS_T1126A_FUNCIONARIO;

IF EXISTS 
(
	SELECT * 
	FROM sys.objects 
	WHERE object_id = OBJECT_ID(N'dbo.GIS_T1126A_FUNCIONARIO')
		AND TYPE IN (N'U')
)
	DROP TABLE dbo.GIS_T1126A_FUNCIONARIO;


-- Criação da tabela

CREATE TABLE dbo.GIS_T1126A_FUNCIONARIO (
	CODIGO INT NOT NULL, 
	NOME VARCHAR (45) NOT NULL,
	VERIFICACAO INT NOT NULL,
	DATA_NASCIMENTO DATE NOT NULL, 
	CPF NUMERIC (11,0) NOT NULL, 
	CELULAR NUMERIC (11,0)NOT NULL,
	EMAIL VARCHAR (45) NULL,
	GENERO CHAR NULL,
	GRAU_ESCOLARIDADE VARCHAR (45) NOT NULL,
	INSTITUICAO_ENSINO VARCHAR (60) NOT NULL,
	INICIO_ENSINO DATE NOT NULL,
	FINAL_ENSINO DATE NOT NULL,
	CONSTRAINT PK_GIS_T1126A_FUNCIONARIO PRIMARY KEY CLUSTERED (CODIGO) WITH FILLFACTOR = 10,
	CONSTRAINT CK_GIS_T1126A_FUNCIONARIO_DATA_NASCIMENTO CHECK (DATEDIFF(YEAR, DATA_NASCIMENTO, GETDATE()) >= 21)
);


----------------------------------------------------------------------------------------------------------------------------


-- TABELA: dbo.GIS_T1126A_DEPEN_FUNC

-- Eliminação da tabela, se existir.


IF EXISTS 
(
	SELECT *
	FROM sys.check_constraints 
	WHERE object_id = OBJECT_ID(N'dbo.CK_GIS_T1126A_DEPEN_FUNC')
		AND parent_object_id = OBJECT_ID(N'dbo.GIS_T1126A_DEPEN_FUNC')
) 
	ALTER TABLE dbo.GIS_T1126A_DEPEN_FUNC
	DROP CONSTRAINT CK_GIS_T1126A_DEPEN_FUNC;

IF EXISTS 
(
	SELECT * 
	FROM sys.objects 
	WHERE object_id = OBJECT_ID(N'dbo.GIS_T1126A_DEPEN_FUNC')
		AND TYPE IN (N'U')
)
	DROP TABLE dbo.GIS_T1126A_DEPEN_FUNC;


-- Criação da tabela

CREATE TABLE dbo.GIS_T1126A_DEPEN_FUNC (
	CODIGO INT NOT NULL, 
	COD_FUNC INT NOT NULL, 
	NOME VARCHAR (45) NOT NULL,
	VERIFICACAO INT NOT NULL,
	DATA_NASCIMENTO DATE NOT NULL, 
	CPF NUMERIC (11,0) NOT NULL, 
	CELULAR NUMERIC (11,0)NOT NULL,
	EMAIL VARCHAR (45) NULL,
	GENERO CHAR NULL,
	GRAU_ESCOLARIDADE VARCHAR (45) NOT NULL,
	INSTITUICAO_ENSINO VARCHAR (60) NOT NULL,
	INICIO_ENSINO DATE NOT NULL,
	FINAL_ENSINO DATE NOT NULL,
	CONSTRAINT PK_GIS_T1126A_DEPEN_FUNC PRIMARY KEY CLUSTERED (CODIGO) WITH FILLFACTOR = 10,
	CONSTRAINT FK_GIS_T1126A_DEPEN_FUNC FOREIGN KEY (COD_FUNC) References dbo.GIS_T1126A_FUNCIONARIO (CODIGO) 
);


----------------------------------------------------------------------------------------------------------------------------


-- TABELA: dbo.GIS_T1126A_MECANICO

-- Eliminação da tabela, se existir.


IF EXISTS 
(
	SELECT *
	FROM sys.check_constraints 
	WHERE object_id = OBJECT_ID(N'dbo.CK_GIS_T1126A_MECANICO')
		AND parent_object_id = OBJECT_ID(N'dbo.GIS_T1126A_MECANICO')
) 
	ALTER TABLE dbo.GIS_T1126A_MECANICO
	DROP CONSTRAINT CK_GIS_T1126A_MECANICO;

IF EXISTS 
(
	SELECT * 
	FROM sys.objects 
	WHERE object_id = OBJECT_ID(N'dbo.GIS_T1126A_MECANICO')
		AND TYPE IN (N'U')
)
	DROP TABLE dbo.GIS_T1126A_MECANICO;


-- Criação da tabela

CREATE TABLE dbo.GIS_T1126A_MECANICO (
	CODIGO INT NOT NULL, 
	COD_FUNC INT NOT NULL,
	CURSO_COMPLEMETAR VARCHAR (100) NOT NULL,
	DATA_CONCLUSAO DATE NULL, 
	TITULO_CONCEDIDO VARCHAR (45) NULL,
	INTUTUICAO VARCHAR (45) NULL,
	ENDERECO VARCHAR (100) NULL,
	TELEFONE_INSTITUICAO DECIMAL(11,0) NULL,
	CARGA_HORARIA INT NULL,
	TIPO_REPARO VARCHAR (45) NULL,
	CONSTRAINT PK_GIS_T1126A_MECANICO PRIMARY KEY CLUSTERED (CODIGO) WITH FILLFACTOR = 10,
	CONSTRAINT FK_GIS_T1126A_MECANICO FOREIGN KEY (COD_FUNC) References dbo.GIS_T1126A_FUNCIONARIO (CODIGO) 
);


----------------------------------------------------------------------------------------------------------------------------


-- TABELA: dbo.GIS_T1126A_VEICULOS_REPARADOS

-- Eliminação da tabela, se existir.


IF EXISTS 
(
	SELECT *
	FROM sys.check_constraints 
	WHERE object_id = OBJECT_ID(N'dbo.CK_GIS_T1126A_VEICULOS_REPARADOS')
		AND parent_object_id = OBJECT_ID(N'dbo.GIS_T1126A_VEICULOS_REPARADOS')
) 
	ALTER TABLE dbo.GIS_T1126A_VEICULOS_REPARADOS
	DROP CONSTRAINT CK_GIS_T1126A_VEICULOS_REPARADOS;

IF EXISTS 
(
	SELECT * 
	FROM sys.objects 
	WHERE object_id = OBJECT_ID(N'dbo.GIS_T1126A_VEICULOS_REPARADOS')
		AND TYPE IN (N'U')
)
	DROP TABLE dbo.GIS_T1126A_VEICULOS_REPARADOS;


-- Criação da tabela

CREATE TABLE dbo.GIS_T1126A_VEICULOS_REPARADOS (
	CODIGO INT NOT NULL, 
	MARCA VARCHAR (45) NOT NULL,
	MODELO VARCHAR (45) NOT NULL, 
	CHASSI VARCHAR (45) NOT NULL, 
	PLACA VARCHAR (7) NOT NULL, 
	ANO_FABRICACAO DATE NOT NULL, 
	COR VARCHAR (20) NOT NULL,
	NOME_PROPRIETARIO VARCHAR (45) NOT NULL,
	ENDERECO_PROPRIETARIO VARCHAR (100) NOT NULL, 
	TELEFONE_PROPRIETARIO DECIMAL (11,0) NOT NULL,
	EMAIL_PROPRIETARIO VARCHAR (45) NOT NULL,
	TIPO_REPARO VARCHAR (45) NOT NULL,
	DATA_INCIO_REPARO DATE NOT NULL,
	DATA_FINAL_REPARO DATE NOT NULL,
	CONSTRAINT PK_GIS_T1126A_VEICULOS_REPARADOS PRIMARY KEY CLUSTERED (CODIGO) WITH FILLFACTOR = 10
);


----------------------------------------------------------------------------------------------------------------------------


-- TABELA: dbo.GIS_T1126A_FUNCINARIO_REPARO

-- Eliminação da tabela, se existir.


IF EXISTS 
(
	SELECT *
	FROM sys.check_constraints 
	WHERE object_id = OBJECT_ID(N'dbo.CK_GIS_T1126A_FUNCINARIO_REPARO')
		AND parent_object_id = OBJECT_ID(N'dbo.GIS_T1126A_FUNCINARIO_REPARO')
) 
	ALTER TABLE dbo.GIS_T1126A_FUNCINARIO_REPARO
	DROP CONSTRAINT CK_GIS_T1126A_FUNCINARIO_REPARO;

IF EXISTS 
(
	SELECT * 
	FROM sys.objects 
	WHERE object_id = OBJECT_ID(N'dbo.GIS_T1126A_FUNCINARIO_REPARO')
		AND TYPE IN (N'U')
)
	DROP TABLE dbo.GIS_T1126A_FUNCINARIO_REPARO;


-- Criação da tabela

CREATE TABLE dbo.GIS_T1126A_FUNCINARIO_REPARO (
	CODIGO INT NOT NULL, 
	COD_FUNC INT NOT NULL,
	COD_VEICULO INT NOT NULL,
	INICIO DATE NOT NULL, 
	TERMINO DATE NOT NULL,
	SALARIO FLOAT NOT NULL,
	HORA_HOMEM FLOAT NOT NULL,
	CONSTRAINT PK_GIS_T1126A_FUNCINARIO_REPARO PRIMARY KEY CLUSTERED (CODIGO) WITH FILLFACTOR = 10,
	CONSTRAINT FK_GIS_T1126A_FUNCINARIO_REPARO FOREIGN KEY (COD_FUNC) References dbo.GIS_T1126A_FUNCIONARIO (CODIGO), 
	CONSTRAINT FK_GIS_T1126A_FUNCINARIO_VEICULO FOREIGN KEY (COD_VEICULO) References dbo.GIS_T1126A_VEICULOS_REPARADOS (CODIGO) 
);



----------------------------------------------------------------------------------------------------------------------------


-- TABELA: dbo.GIS_T1126A_FORNECEDORES

-- Eliminação da tabela, se existir.


IF EXISTS 
(
	SELECT *
	FROM sys.check_constraints 
	WHERE object_id = OBJECT_ID(N'dbo.CK_GIS_T1126A_FORNECEDORES')
		AND parent_object_id = OBJECT_ID(N'dbo.GIS_T1126A_FORNECEDORES')
) 
	ALTER TABLE dbo.GIS_T1126A_FORNECEDORES
	DROP CONSTRAINT CK_GIS_T1126A_FORNECEDORES;

IF EXISTS 
(
	SELECT * 
	FROM sys.objects 
	WHERE object_id = OBJECT_ID(N'dbo.GIS_T1126A_FORNECEDORES')
		AND TYPE IN (N'U')
)
	DROP TABLE dbo.GIS_T1126A_FORNECEDORES;


-- Criação da tabela

CREATE TABLE dbo.GIS_T1126A_FORNECEDORES (
	CODIGO INT NOT NULL, 
	NOME VARCHAR (45) NOT NULL,
	PEÇA VARCHAR (45) NOT NULL,
	COD_PAIS NUMERIC (3,0) NOT NULL,
	UF CHAR (3) NOT NULL, 
	CIDADE CHAR (45) NOT NULL, 
	CONSTRAINT PK_GIS_T1126A_FORNECEDORES PRIMARY KEY CLUSTERED (CODIGO) WITH FILLFACTOR = 10,
	CONSTRAINT FK_GIS_T1126A_FORNECEDORES FOREIGN KEY (COD_PAIS, UF, CIDADE) References dbo.GIS_TB07S001_CIDADES (cod_pais, uf, cidade) 
);



----------------------------------------------------------------------------------------------------------------------------


-- TABELA: dbo.GIS_T1126A_SEGURO

-- Eliminação da tabela, se existir.


IF EXISTS 
(
	SELECT *
	FROM sys.check_constraints 
	WHERE object_id = OBJECT_ID(N'dbo.CK_GIS_T1126A_SEGURO')
		AND parent_object_id = OBJECT_ID(N'dbo.GIS_T1126A_SEGURO')
) 
	ALTER TABLE dbo.GIS_T1126A_SEGURO
	DROP CONSTRAINT CK_GIS_T1126A_SEGURO;

IF EXISTS 
(
	SELECT * 
	FROM sys.objects 
	WHERE object_id = OBJECT_ID(N'dbo.GIS_T1126A_SEGURO')
		AND TYPE IN (N'U')
)
	DROP TABLE dbo.GIS_T1126A_SEGURO;


-- Criação da tabela

CREATE TABLE dbo.GIS_T1126A_SEGURO (
	CODIGO INT NOT NULL, 
	NOME VARCHAR (45) NOT NULL,
	VALIDADE_CONVENIO DATE NOT NULL,
	CONSTRAINT PK_GIS_T1126A_SEGURO PRIMARY KEY CLUSTERED (CODIGO) WITH FILLFACTOR = 10, 
);
----------------------------------------------------------------------------------------------------------------------------


-- TABELA: dbo.GIS_T1126A_ORCAMENTO

-- Eliminação da tabela, se existir.


IF EXISTS 
(
	SELECT *
	FROM sys.check_constraints 
	WHERE object_id = OBJECT_ID(N'dbo.CK_GIS_T1126A_ORCAMENTO')
		AND parent_object_id = OBJECT_ID(N'dbo.GIS_T1126A_ORCAMENTO')
) 
	ALTER TABLE dbo.GIS_T1126A_ORCAMENTO
	DROP CONSTRAINT CK_GIS_T1126A_ORCAMENTO;

IF EXISTS 
(
	SELECT * 
	FROM sys.objects 
	WHERE object_id = OBJECT_ID(N'dbo.GIS_T1126A_ORCAMENTO')
		AND TYPE IN (N'U')
)
	DROP TABLE dbo.GIS_T1126A_ORCAMENTO;


-- Criação da tabela

CREATE TABLE dbo.GIS_T1126A_ORCAMENTO (
	CODIGO INT NOT NULL, 
	NOME VARCHAR (45) NOT NULL,
	VALOR FLOAT NOT NULL,
	CONSTRAINT PK_GIS_T1126A_ORCAMENTO PRIMARY KEY CLUSTERED (CODIGO) WITH FILLFACTOR = 10, 
);

----------------------------------------------------------------------------------------------------------------------------

-- TABELA: dbo.GIS_T1126A_CLIENTE

-- Eliminação da tabela, se existir.


IF EXISTS 
(
	SELECT *
	FROM sys.check_constraints 
	WHERE object_id = OBJECT_ID(N'dbo.CK_GIS_T1126A_CLIENTE')
		AND parent_object_id = OBJECT_ID(N'dbo.GIS_T1126A_CLIENTE')
) 
	ALTER TABLE dbo.GIS_T1126A_CLIENTE
	DROP CONSTRAINT CK_GIS_T1126A_CLIENTE;

IF EXISTS 
(
	SELECT * 
	FROM sys.objects 
	WHERE object_id = OBJECT_ID(N'dbo.GIS_T1126A_CLIENTE')
		AND TYPE IN (N'U')
)
	DROP TABLE dbo.GIS_T1126A_CLIENTE;


-- Criação da tabela

CREATE TABLE dbo.GIS_T1126A_CLIENTE (
	CODIGO INT NOT NULL, 
	NOME VARCHAR (45) NOT NULL,
	VERIFICACAO INT NOT NULL,
	DATA_NASCIMENTO DATE NOT NULL, 
	CPF NUMERIC (11,0) NOT NULL, 
	CELULAR NUMERIC (11,0)NOT NULL,
	EMAIL VARCHAR (45) NULL,
	GENERO CHAR NULL,
	CONSTRAINT PK_GIS_T1126A_CLIENTE PRIMARY KEY CLUSTERED (CODIGO) WITH FILLFACTOR = 10,
	CONSTRAINT CK_GIS_T1126A_CLIENTE_DATA_NASCIMENTO CHECK (DATEDIFF(YEAR, DATA_NASCIMENTO, GETDATE()) >= 21)
);


----------------------------------------------------------------------------------------------------------------------------


-- TABELA: dbo.GIS_T1126A_DEPEN_CLIENTE

-- Eliminação da tabela, se existir.


IF EXISTS 
(
	SELECT *
	FROM sys.check_constraints 
	WHERE object_id = OBJECT_ID(N'dbo.CK_GIS_T1126A_DEPEN_CLIENTE')
		AND parent_object_id = OBJECT_ID(N'dbo.GIS_T1126A_DEPEN_CLIENTE')
) 
	ALTER TABLE dbo.GIS_T1126A_DEPEN_CLIENTE
	DROP CONSTRAINT CK_GIS_T1126A_DEPEN_CLIENTE;

IF EXISTS 
(
	SELECT * 
	FROM sys.objects 
	WHERE object_id = OBJECT_ID(N'dbo.GIS_T1126A_DEPEN_CLIENTE')
		AND TYPE IN (N'U')
)
	DROP TABLE dbo.GIS_T1126A_DEPEN_CLIENTE;


-- Criação da tabela

CREATE TABLE dbo.GIS_T1126A_DEPEN_CLIENTE (
	CODIGO INT NOT NULL, 
	COD_CLIENTE INT NOT NULL, 
	NOME VARCHAR (45) NOT NULL,
	VERIFICACAO INT NOT NULL,
	DATA_NASCIMENTO DATE NOT NULL, 
	CPF NUMERIC (11,0) NOT NULL, 
	CELULAR NUMERIC (11,0)NOT NULL,
	EMAIL VARCHAR (45) NULL,
	GENERO CHAR NULL,
	CONSTRAINT PK_GIS_T1126A_DEPEN_CLIENTE PRIMARY KEY CLUSTERED (CODIGO) WITH FILLFACTOR = 10,
	CONSTRAINT FK_GIS_T1126A_DEPEN_CLIENTE FOREIGN KEY (COD_CLIENTE) References dbo.GIS_T1126A_CLIENTE (CODIGO) 
);


----------------------------------------------------------------------------------------------------------------------------


-- TABELA: dbo.GIS_T1126A_VEICULOS

-- Eliminação da tabela, se existir.


IF EXISTS 
(
	SELECT *
	FROM sys.check_constraints 
	WHERE object_id = OBJECT_ID(N'dbo.CK_GIS_T1126A_VEICULOS')
		AND parent_object_id = OBJECT_ID(N'dbo.GIS_T1126A_VEICULOS')
) 
	ALTER TABLE dbo.GIS_T1126A_VEICULOS
	DROP CONSTRAINT CK_GIS_T1126A_VEICULOS;

IF EXISTS 
(
	SELECT * 
	FROM sys.objects 
	WHERE object_id = OBJECT_ID(N'dbo.GIS_T1126A_VEICULOS')
		AND TYPE IN (N'U')
)
	DROP TABLE dbo.GIS_T1126A_VEICULOS;


-- Criação da tabela

CREATE TABLE dbo.GIS_T1126A_VEICULOS (
	CODIGO INT NOT NULL, 
	COD_CLIENTE INT NOT NULL, 
	COD_MOTORISTA INT NOT NULL,
	USO VARCHAR (45) NOT NULL,
	GARAGEM VARCHAR (45) NOT NULL,
	ALARME CHAR NOT NULL,
	CONSTRAINT PK_GIS_T1126A_VEICULOS PRIMARY KEY CLUSTERED (CODIGO) WITH FILLFACTOR = 10,
	CONSTRAINT FK_GIS_T1126A_VEICULOS_CLIENTE FOREIGN KEY (COD_CLIENTE) References dbo.GIS_T1126A_CLIENTE (CODIGO),
	CONSTRAINT FK_GIS_T1126A_VEICULOS_MOTORISTA FOREIGN KEY (COD_MOTORISTA) References dbo.GIS_T1001C_MOTORISTA (CODIGO)
);